### ISSUE TITLE
Add charge kwarg

### ISSUE THREAD

**Issue by JimmyRushing** [cmelab/morphct#8] opened 2021-06-16 18:53 UTC
![Screen Shot 2021-06-10 at 1 46 03 PM](https://user-images.githubusercontent.com/66091001/122275584-1b6b3780-cea1-11eb-91ec-0662dc4bf6d2.png)

when providing the yellow and the pink as chromophores, I get an electron spin error from set_energyvalues. This will probably crop up often if we are creating intramolecular chromophores?

**Comment by erjank** [comment] 2021-06-16 19:11
This is the thing that'll be solved by adding hydrogens that we talked
about yesterday, correct?

**Comment by JimmyRushing** [comment] 2021-06-16 19:59
yea

**Comment by jennyfothergill** [comment] 2021-06-17 20:54
![Screen Shot 2021-06-17 at 2 50 15 PM](https://user-images.githubusercontent.com/39961845/122470713-9e60c080-cf7b-11eb-84ce-b8259306cc0a.png)
I think this issue is caused by this part here. This carbon atom has three bonds to it, which means one of its bonds is a double-bond. If we replace that with a hydrogen, there will be some issue when running QCC. These issues could be fixed by adding a charge argument that would be passed to QCC or by changing the defined chromophores.

**Comment by JimmyRushing** [comment] 2021-06-18 17:33
![Screen Shot 2021-06-18 at 11 25 24 AM](https://user-images.githubusercontent.com/66091001/122596949-e1786d80-d027-11eb-9e55-0cb2797e7169.png)

![Screen Shot 2021-06-18 at 11 31 23 AM](https://user-images.githubusercontent.com/66091001/122597533-b80c1180-d028-11eb-9434-4d133a8f02ea.png)

![Screen Shot 2021-06-18 at 11 32 03 AM](https://user-images.githubusercontent.com/66091001/122597593-cfe39580-d028-11eb-89c3-87915c2cb17d.png)

A little more context: If I assign that little guy to a cromophore, the workflow breaks down trying to get_homolumo() for the chromo with the extra atom (error shown). the get_humolumo() succeeds for the other chromo as seen in the third screenshot. If I assign the little fella to the other chromophore. Then its get_homolumo fails. 

If I leave it  out, I get the original error.

**Comment by JimmyRushing** [comment] 2021-06-18 17:48
UPDATE:  The workflow runs if I leave the little fella out.  With a transfer integral of 0.000 if I call them "acceptors" and .563 if i call them "donors"

**Comment by jennyfothergill** [comment] 2021-06-21 21:28
![IMG_20210621_151713952](https://user-images.githubusercontent.com/39961845/122830010-f9105a00-d2a4-11eb-8331-27e080851089.jpg)
OK, I had to do a little drawing to think about where all the double bonds were in this fragment. Hopefully my chicken scratch makes sense here, but basically the end result is that I think if we want to assign this fragment to a chromophore, we should include a charge. I will work on adding this!

**Closed** 2021-07-02 21:48 UTC
